name: Unity Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2023.1.0f1
    - name: Build Unity project
      uses: game-ci/unity-builder@v2
      with:
        targetPlatform: StandaloneWindows64
        buildName: UrbanMechanicAdventure
